descriptor_extension: yml
version: '0.5'
files:
- path: ns_one_connection_haproxy.yml
  type: application/vnd.5gtango.nsd
  tags:
  - eu.5gtango
- path: vnfd_one_connection_haproxy.yml
  type: application/vnd.5gtango.vnfd
  tags:
  - eu.5gtango
package:
  name: ns-one-connection-haproxy
  version: '0.1'
  maintainer: Anush Shankar
  vendor: de.upb
  description: Test service for benchmarking experiments.

